name: 'Modules'

on:
  workflow_dispatch:
  push:
    paths:
      - 'modules/**'
    branches:
      - 'main'
      - 'v0.6.0'

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  REGISTRY_NAME: 'br:biceps.azurecr.io'

jobs:
  ##################
  #   Publishing   #
  ##################
  job_publish_module:
    name: 'Publishing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Azure login
      - uses: Azure/login@v1.1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      # Publish to bicep registry
      - name: 'Publishing'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az bicep install
            [[ ${{github.ref_name}} == main ]] && tagName=latest || tagName=${{github.ref_name}}
            find modules/ -depth -regex ".*\.bicep" -type f -not -path "*.bicep/*" | sort -n
            find modules/ -depth -regex ".*\.bicep" -type f -not -path "*.bicep/*" | sort -nr
            for filename in `find modules/ -depth -regex ".*\.bicep" -type f -not -path "*.bicep/*" | sort -n`; do  echo `dirname $filename` && az bicep publish --file $filename --target ${{env.REGISTRY_NAME}}/`dirname $filename | tr '[:upper:]' '[:lower:]'`:$tagName; done
