name: 'Resources: ResourceGroups'

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  REGISTRY_NAME: 'br:michaelburch101.azurecr.io'

jobs:
  ##################
  #   Publishing   #
  ##################
  job_publish_module:
    name: 'Publishing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Azure login
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Publish to bicep registry
      - name: 'Publishing'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az bicep install
            for filename in `ls modules/*.bicep`; do  az bicep publish --file $filename --target ${{env.REGISTRY_NAME}}/bicep/modules/`basename $filename .bicep | tr '[:upper:]' '[:lower:]'`:${{github.ref_name}}; done
